//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::GameStatus;
use super::sea_orm_active_enums::PhaseKind;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "games"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub created_at: TimeDateTimeWithTimeZone,
    pub host_player_id: i64,
    pub name: String,
    pub currency: String,
    pub max_players: i16,
    pub small_blind: i64,
    pub big_blind: i64,
    pub ante: i64,
    pub rake_bps: i16,
    pub status: GameStatus,
    pub current_hand_id: Option<i64>,
    pub current_state_hash: Option<Vec<u8>>,
    pub current_phase: Option<PhaseKind>,
    pub default_hand_config_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreatedAt,
    HostPlayerId,
    Name,
    Currency,
    MaxPlayers,
    SmallBlind,
    BigBlind,
    Ante,
    RakeBps,
    Status,
    CurrentHandId,
    CurrentStateHash,
    CurrentPhase,
    DefaultHandConfigId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Events,
    GamePlayers,
    GameShufflers,
    HandConfigs,
    HandPlayer,
    Hands,
    Players,
    TableSnapshots,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::HostPlayerId => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::Text.def(),
            Self::Currency => ColumnType::Text.def(),
            Self::MaxPlayers => ColumnType::SmallInteger.def(),
            Self::SmallBlind => ColumnType::BigInteger.def(),
            Self::BigBlind => ColumnType::BigInteger.def(),
            Self::Ante => ColumnType::BigInteger.def(),
            Self::RakeBps => ColumnType::SmallInteger.def(),
            Self::Status => GameStatus::db_type().get_column_type().to_owned().def(),
            Self::CurrentHandId => ColumnType::BigInteger.def().null(),
            Self::CurrentStateHash => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::CurrentPhase => PhaseKind::db_type()
                .get_column_type()
                .to_owned()
                .def()
                .null(),
            Self::DefaultHandConfigId => ColumnType::BigInteger.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Events => Entity::has_many(super::events::Entity).into(),
            Self::GamePlayers => Entity::has_many(super::game_players::Entity).into(),
            Self::GameShufflers => Entity::has_many(super::game_shufflers::Entity).into(),
            Self::HandConfigs => Entity::belongs_to(super::hand_configs::Entity)
                .from(Column::DefaultHandConfigId)
                .to(super::hand_configs::Column::Id)
                .into(),
            Self::HandPlayer => Entity::has_many(super::hand_player::Entity).into(),
            Self::Hands => Entity::belongs_to(super::hands::Entity)
                .from(Column::CurrentHandId)
                .to(super::hands::Column::Id)
                .into(),
            Self::Players => Entity::belongs_to(super::players::Entity)
                .from(Column::HostPlayerId)
                .to(super::players::Column::Id)
                .into(),
            Self::TableSnapshots => Entity::has_many(super::table_snapshots::Entity).into(),
        }
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::game_players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GamePlayers.def()
    }
}

impl Related<super::game_shufflers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameShufflers.def()
    }
}

impl Related<super::hand_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HandConfigs.def()
    }
}

impl Related<super::hand_player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HandPlayer.def()
    }
}

impl Related<super::hands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hands.def()
    }
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Players.def()
    }
}

impl Related<super::table_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TableSnapshots.def()
    }
}

impl Related<super::shufflers::Entity> for Entity {
    fn to() -> RelationDef {
        super::game_shufflers::Relation::Shufflers.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::game_shufflers::Relation::Games.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
